# 
# include ../../../defs.mk
# 
# SRCS+=testutils.c
# 
# include ../../../mk/os161.lib.mk
# 
# LIB=testutils

#
# Makefile for test utility library
#

TOP=../../..
.include "$(TOP)/mk/os161.config.mk"

SRCS+= testutils.c
	
# Name of the library.
LIB=testutils

# Let the templates do most of the work.
.include  "$(TOP)/mk/os161.lib.mk"


