#
# Makefile for user/uw-testbin
#

TOP=../..
.include "$(TOP)/mk/os161.config.mk"

SUBDIRS= lib files1 files2 conc-io writeread \
	argtest segments syscall vm-funcs vm-crash1 vm-crash2 vm-crash3 \
	vm-data1 vm-data2 vm-data3 vm-stack1 vm-stack2 vm-stackgrow \
	vm-mix1 vm-mix1-exec vm-mix1-fork vm-mix2 \
	romemwrite sparse exec-sparse tlbfaulter \
	onefork widefork pidcheck \
	xhog yhog zhog hogparty argtesttest

.include "$(TOP)/mk/os161.subdir.mk"
